version: "3.4"

services:
  # app:
  #   container_name: app-docker
  #   build:
  #     context: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env.dev
  #   # logging:
  #   #   driver: fluentd
  #   #   options:
  #   #     fluentd-address: localhost:24224
  #   depends_on:
  #     - otel-collector
  #   networks:
  #     - observability-network

  # pushgateway:
  #   container_name: pushgateway
  #   build:
  #     context: templates/pushgateway
  #   ports:
  #     - 8001:8001
  #   restart: always
  #   networks:
  #     - observability-network
  
  # prometheus:
  #   container_name: prometheus
  #   build:
  #     context: templates/prometheus
  #   volumes:
  #     - ./templates/prometheus:/etc/prometheus
  #   ports:
  #     - 8002:8002
  #   restart: always
  #   networks:
  #     - observability-network

  tempo:
    container_name: tempo
    build:
      context: templates/tempo
    ports:
      - 8003:8003
      - 8004:8004
      - 8008:8008
    restart: always
    networks:
      - observability-network
  
  grafana:
    container_name: grafana
    build:
      context: templates/grafana
    ports:
      - 8005:3000
    restart: always
    networks:
      - observability-network
  
  loki:
    container_name: loki
    build:
      context: templates/loki
    cpus: 0.1
    mem_limit: 100m
    env_file:
      - .env.dev
    ports:
      - 8006:8006
      - 8009:8009
    restart: always
    networks:
      - observability-network
  
  # fluentbit:
  #   container_name: fluentbit
  #   build:
  #     context: templates/fluentbit
  #   cpus: 0.1
  #   mem_limit: 100m
  #   env_file:
  #     - .env.dev
  #   ports:
  #     - 24224:24224
  #   restart: always
  #   volumes:
  #     - ./templates/fluentbit/.logs:/logs/
  #   networks:
  #     - observability-network
  #   depends_on:
  #     - loki
  
  otel-collector:
    container_name: otel-collector
    cpus: 0.1
    mem_limit: 100m
    build:
      context: templates/otelCollector
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    restart: always
    networks:
      - observability-network

networks:
  observability-network:
    external: true