# /tmp/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed

  otlphttp:
    endpoint: "http://tempo:8008"

  loki:
    endpoint: http://loki:8006/loki/api/v1/push

processors:
  batch:

  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: service_name,severityText,traceID,spanID

  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name,severityText,traceID,spanID
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [loki, debug]
      processors: [batch,attributes,resource]